version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery
    networks:
      - fuel-pass-network

  discovery:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    networks:
      - fuel-pass-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - user-db
    networks:
      - fuel-pass-network

  user-db:
    image: postgres:13
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - fuel-pass-network

  vehicle-service:
    build:
      context: ./vehicle-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - vehicle-db
    networks:
      - fuel-pass-network

  vehicle-db:
    image: postgres:13
    environment:
      POSTGRES_DB: vehicledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - fuel-pass-network

  fuel-station-management-service:
    build:
      context: ./fuel-station-management-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - fuel-station-db
    networks:
      - fuel-pass-network

  fuel-station-db:
    image: postgres:13
    environment:
      POSTGRES_DB: fuelstationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - fuel-pass-network

  fuel-quota-service:
    build:
      context: ./fuel-quota-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - fuel-pass-network

  qr-code-generation-service:
    build:
      context: ./qr-code-generation-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - fuel-pass-network

  qr-code-scanning-service:
    build:
      context: ./qr-code-scanning-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - fuel-pass-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - fuel-pass-network

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - admin-db
    networks:
      - fuel-pass-network

  admin-db:
    image: postgres:13
    environment:
      POSTGRES_DB: adminservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - fuel-pass-network

  mtd-integration-service:
    build:
      context: ./mtd-integration-service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - fuel-pass-network

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - fuel-pass-network

networks:
  fuel-pass-network:
    driver: bridge
