server:
  port: 9001

spring:
  application:
    name: api-gateway

#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
#        - id: vehicle-service
#          uri: lb://vehicle-service
#          predicates:
#            - Path=/vehicles/**
#        - id: fuel-station-service
#          uri: lb://fuel-station-management-service
#          predicates:
#            - Path=/fuelstations/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

#  zipkin:
#    base-url: http://zipkin:9411
#  sleuth:
#    sampler:
#      probability: 1.0