eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0