# user-service.yml
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5432/userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8081

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#logging:
#  level:
#    org.springframework: INFO
#    com.fuelpass.userservice: DEBUG

