server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://fuelquota-db:5432/fuelquotadb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  bootstrap-servers: kafka:9092

zipkin:
  base-url: http://zipkin:9411
