
server:
  port: 8084

spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fuel_station
    username: postgres
    password: sada1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
