server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:postgresql://admin-db:5432/adminservice
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

zipkin:
  base-url: http://zipkin:9411
