server:
  port: 8083

  application:
    name: motor-traffic-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

spring:
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
